version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      # Run this compose file from homeassistant/configs, or replace the
      # source with the absolute path to this configuration directory.
      - .:/config
      - /etc/localtime:/etc/localtime:ro
      - /srv/juggle_highscores:/config/www/juggle:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
